# µÇÂ¼ÃÜÂë£ºadmin/adminadmin
version: "3"

services:
  qbittorrent:
    container_name: qbittorrent
    # image: linuxserver/qbittorrent:latest
    image: johngong/qbittorrent:qee_4.2.1.10
    restart: unless-stopped
    ports:
      - 8001:8001
    environment:
      - PUID=0
      - PGID=0
      - WEBUIPORT=8001
    volumes:
      - ./conf:/config
      - /mnt/storage/storage/downloads:/Downloads:rw
